/*
|-----------------------------
| Data for table `countries`.
|-----------------------------
*/
    LOCK TABLES `countries` WRITE;
    INSERT INTO `countries`
    VALUES   (  4,'AF','AFG',0,'Afghanistan')
            ,(  8,'AL','ALB',0,'Albania')
            ,( 10,'AQ','ATA',0,'Antarctica')
            ,( 12,'DZ','DZA',0,'Algeria')
            ,( 16,'AS','ASM',0,'American Samoa')
            ,( 20,'AD','AND',0,'Andorra')
            ,( 24,'AO','AGO',0,'Angola')
            ,( 28,'AG','ATG',0,'Antigua and Barbuda')
            ,( 31,'AZ','AZE',0,'Azerbaijan')
            ,( 32,'AR','ARG',0,'Argentina')
            ,( 36,'AU','AUS',0,'Australia')
            ,( 40,'AT','AUT',0,'Austria')
            ,( 44,'BS','BHS',0,'Bahamas')
            ,( 48,'BH','BHR',0,'Bahrain')
            ,( 50,'BD','BGD',0,'Bangladesh')
            ,( 51,'AM','ARM',0,'Armenia')
            ,( 52,'BB','BRB',0,'Barbados')
            ,( 56,'BE','BEL',0,'Belgium')
            ,( 60,'BM','BMU',0,'Bermuda')
            ,( 64,'BT','BTN',0,'Bhutan')
            ,( 68,'BO','BOL',0,'Bolivia (Plurinational State of)')
            ,( 70,'BA','BIH',0,'Bosnia and Herzegovina')
            ,( 72,'BW','BWA',0,'Botswana')
            ,( 74,'BV','BVT',0,'Bouvet Island')
            ,( 76,'BR','BRA',0,'Brazil')
            ,( 84,'BZ','BLZ',0,'Belize')
            ,( 86,'IO','IOT',0,'British Indian Ocean Territory')
            ,( 90,'SB','SLB',0,'Solomon Islands')
            ,( 92,'VG','VGB',0,'Virgin Islands (British)')
            ,( 96,'BN','BRN',0,'Brunei Darussalam')
            ,(100,'BG','BGR',0,'Bulgaria')
            ,(104,'MM','MMR',0,'Myanmar')
            ,(108,'BI','BDI',0,'Burundi')
            ,(112,'BY','BLR',0,'Belarus')
            ,(116,'KH','KHM',0,'Cambodia')
            ,(120,'CM','CMR',0,'Cameroon')
            ,(124,'CA','CAN',0,'Canada')
            ,(132,'CV','CPV',0,'Cabo Verde')
            ,(136,'KY','CYM',0,'Cayman Islands')
            ,(140,'CF','CAF',0,'Central African Republic')
            ,(144,'LK','LKA',0,'Sri Lanka')
            ,(148,'TD','TCD',0,'Chad')
            ,(152,'CL','CHL',0,'Chile')
            ,(156,'CN','CHN',0,'China')
            ,(158,'TW','TWN',0,'Taiwan, Province of China[a]')
            ,(162,'CX','CXR',0,'Christmas Island')
            ,(166,'CC','CCK',0,'Cocos (Keeling) Islands')
            ,(170,'CO','COL',0,'Colombia')
            ,(174,'KM','COM',0,'Comoros')
            ,(175,'YT','MYT',0,'Mayotte')
            ,(178,'CG','COG',0,'Congo')
            ,(180,'CD','COD',0,'Congo (Democratic Republic of the)')
            ,(184,'CK','COK',0,'Cook Islands')
            ,(188,'CR','CRI',0,'Costa Rica')
            ,(191,'HR','HRV',0,'Croatia')
            ,(192,'CU','CUB',0,'Cuba')
            ,(196,'CY','CYP',0,'Cyprus')
            ,(203,'CZ','CZE',0,'Czech Republic')
            ,(204,'BJ','BEN',0,'Benin')
            ,(208,'DK','DNK',0,'Denmark')
            ,(212,'DM','DMA',0,'Dominica')
            ,(214,'DO','DOM',0,'Dominican Republic')
            ,(218,'EC','ECU',0,'Ecuador')
            ,(222,'SV','SLV',0,'El Salvador')
            ,(226,'GQ','GNQ',0,'Equatorial Guinea')
            ,(231,'ET','ETH',0,'Ethiopia')
            ,(232,'ER','ERI',0,'Eritrea')
            ,(233,'EE','EST',0,'Estonia')
            ,(234,'FO','FRO',0,'Faroe Islands')
            ,(238,'FK','FLK',0,'Falkland Islands (Malvinas)')
            ,(239,'GS','SGS',0,'South Georgia and the South Sandwich Islands')
            ,(242,'FJ','FJI',0,'Fiji')
            ,(246,'FI','FIN',0,'Finland')
            ,(248,'AX','ALA',0,'Åland Islands')
            ,(250,'FR','FRA',0,'France')
            ,(254,'GF','GUF',0,'French Guiana')
            ,(258,'PF','PYF',0,'French Polynesia')
            ,(260,'TF','ATF',0,'French Southern Territories')
            ,(262,'DJ','DJI',0,'Djibouti')
            ,(266,'GA','GAB',0,'Gabon')
            ,(268,'GE','GEO',0,'Georgia')
            ,(270,'GM','GMB',0,'Gambia')
            ,(275,'PS','PSE',0,'Palestine, State of')
            ,(276,'DE','DEU',0,'Germany')
            ,(288,'GH','GHA',0,'Ghana')
            ,(292,'GI','GIB',0,'Gibraltar')
            ,(296,'KI','KIR',0,'Kiribati')
            ,(300,'GR','GRC',0,'Greece')
            ,(304,'GL','GRL',0,'Greenland')
            ,(308,'GD','GRD',0,'Grenada')
            ,(312,'GP','GLP',0,'Guadeloupe')
            ,(316,'GU','GUM',0,'Guam')
            ,(320,'GT','GTM',0,'Guatemala')
            ,(324,'GN','GIN',0,'Guinea')
            ,(328,'GY','GUY',0,'Guyana')
            ,(332,'HT','HTI',0,'Haiti')
            ,(334,'HM','HMD',0,'Heard Island and McDonald Islands')
            ,(336,'VA','VAT',0,'Holy See')
            ,(340,'HN','HND',0,'Honduras')
            ,(344,'HK','HKG',0,'Hong Kong')
            ,(348,'HU','HUN',0,'Hungary')
            ,(352,'IS','ISL',0,'Iceland')
            ,(356,'IN','IND',0,'India')
            ,(360,'ID','IDN',0,'Indonesia')
            ,(364,'IR','IRN',0,'Iran (Islamic Republic of)')
            ,(368,'IQ','IRQ',0,'Iraq')
            ,(372,'IE','IRL',0,'Ireland')
            ,(376,'IL','ISR',0,'Israel')
            ,(380,'IT','ITA',0,'Italy')
            ,(384,'CI','CIV',0,'Cªte d\'Ivoire')
            ,(388,'JM','JAM',0,'Jamaica')
            ,(392,'JP','JPN',0,'Japan')
            ,(398,'KZ','KAZ',0,'Kazakhstan')
            ,(400,'JO','JOR',0,'Jordan')
            ,(404,'KE','KEN',0,'Kenya')
            ,(408,'KP','PRK',0,'Korea (Democratic People\'s Republic of)')
            ,(410,'KR','KOR',0,'Korea (Republic of)')
            ,(414,'KW','KWT',0,'Kuwait')
            ,(417,'KG','KGZ',0,'Kyrgyzstan')
            ,(418,'LA','LAO',0,'Lao People\'s Democratic Republic')
            ,(422,'LB','LBN',0,'Lebanon')
            ,(426,'LS','LSO',0,'Lesotho')
            ,(428,'LV','LVA',0,'Latvia')
            ,(430,'LR','LBR',0,'Liberia')
            ,(434,'LY','LBY',0,'Libya')
            ,(438,'LI','LIE',0,'Liechtenstein')
            ,(440,'LT','LTU',0,'Lithuania')
            ,(442,'LU','LUX',0,'Luxembourg')
            ,(446,'MO','MAC',0,'Macao')
            ,(450,'MG','MDG',0,'Madagascar')
            ,(454,'MW','MWI',0,'Malawi')
            ,(458,'MY','MYS',0,'Malaysia')
            ,(462,'MV','MDV',0,'Maldives')
            ,(466,'ML','MLI',0,'Mali')
            ,(470,'MT','MLT',0,'Malta')
            ,(474,'MQ','MTQ',0,'Martinique')
            ,(478,'MR','MRT',0,'Mauritania')
            ,(480,'MU','MUS',0,'Mauritius')
            ,(484,'MX','MEX',0,'Mexico')
            ,(492,'MC','MCO',0,'Monaco')
            ,(496,'MN','MNG',0,'Mongolia')
            ,(498,'MD','MDA',0,'Moldova (Republic of)')
            ,(499,'ME','MNE',0,'Montenegro')
            ,(500,'MS','MSR',0,'Montserrat')
            ,(504,'MA','MAR',0,'Morocco')
            ,(508,'MZ','MOZ',0,'Mozambique')
            ,(512,'OM','OMN',0,'Oman')
            ,(516,'NA','NAM',0,'Namibia')
            ,(520,'NR','NRU',0,'Nauru')
            ,(524,'NP','NPL',0,'Nepal')
            ,(528,'NL','NLD',0,'Netherlands')
            ,(531,'CW','CUW',0,'Curaçao')
            ,(533,'AW','ABW',0,'Aruba')
            ,(534,'SX','SXM',0,'SINT Maarten (Dutch part)')
            ,(535,'BQ','BES',0,'Bonaire, SINT Eustatius and Saba')
            ,(540,'NC','NCL',0,'New Caledonia')
            ,(548,'VU','VUT',0,'Vanuatu')
            ,(554,'NZ','NZL',0,'New Zealand')
            ,(558,'NI','NIC',0,'Nicaragua')
            ,(562,'NE','NER',0,'Niger')
            ,(566,'NG','NGA',0,'Nigeria')
            ,(570,'NU','NIU',0,'Niue')
            ,(574,'NF','NFK',0,'Norfolk Island')
            ,(578,'NO','NOR',0,'Norway')
            ,(580,'MP','MNP',0,'Northern Mariana Islands')
            ,(581,'UM','UMI',0,'United States Minor Outlying Islands')
            ,(583,'FM','FSM',0,'Micronesia (Federated States of)')
            ,(584,'MH','MHL',0,'Marshall Islands')
            ,(585,'PW','PLW',0,'Palau')
            ,(586,'PK','PAK',0,'Pakistan')
            ,(591,'PA','PAN',0,'Panama')
            ,(598,'PG','PNG',0,'Papua New Guinea')
            ,(600,'PY','PRY',0,'Paraguay')
            ,(604,'PE','PER',0,'Peru')
            ,(608,'PH','PHL',0,'Philippines')
            ,(612,'PN','PCN',0,'Pitcairn')
            ,(616,'PL','POL',0,'Poland')
            ,(620,'PT','PRT',0,'Portugal')
            ,(624,'GW','GNB',0,'Guinea-Bissau')
            ,(626,'TL','TLS',0,'Timor-Leste')
            ,(630,'PR','PRI',0,'Puerto Rico')
            ,(634,'QA','QAT',0,'Qatar')
            ,(638,'RE','REU',0,'R_union')
            ,(642,'RO','ROU',0,'Romania')
            ,(643,'RU','RUS',0,'Russian Federation')
            ,(646,'RW','RWA',0,'Rwanda')
            ,(652,'BL','BLM',0,'SaINT Barth_lemy')
            ,(654,'SH','SHN',0,'SaINT Helena, Ascension and Tristan da Cunha')
            ,(659,'KN','KNA',0,'SaINT Kitts and Nevis')
            ,(660,'AI','AIA',0,'Anguilla')
            ,(662,'LC','LCA',0,'SaINT Lucia')
            ,(663,'MF','MAF',0,'SaINT Martin (French part)')
            ,(666,'PM','SPM',0,'SaINT Pierre and Miquelon')
            ,(670,'VC','VCT',0,'SaINT Vincent and the Grenadines')
            ,(674,'SM','SMR',0,'San Marino')
            ,(678,'ST','STP',0,'Sao Tome and Principe')
            ,(682,'SA','SAU',0,'Saudi Arabia')
            ,(686,'SN','SEN',0,'Senegal')
            ,(688,'RS','SRB',0,'Serbia')
            ,(690,'SC','SYC',0,'Seychelles')
            ,(694,'SL','SLE',0,'Sierra Leone')
            ,(702,'SG','SGP',0,'Singapore')
            ,(703,'SK','SVK',0,'Slovakia')
            ,(704,'VN','VNM',0,'Viet Nam')
            ,(705,'SI','SVN',0,'Slovenia')
            ,(706,'SO','SOM',0,'Somalia')
            ,(710,'ZA','ZAF',0,'South Africa')
            ,(716,'ZW','ZWE',0,'Zimbabwe')
            ,(724,'ES','ESP',0,'Spain')
            ,(728,'SS','SSD',0,'South Sudan')
            ,(729,'SD','SDN',0,'Sudan')
            ,(732,'EH','ESH',0,'Western Sahara')
            ,(740,'SR','SUR',0,'Suriname')
            ,(744,'SJ','SJM',0,'Svalbard and Jan Mayen')
            ,(748,'SZ','SWZ',0,'Swaziland')
            ,(752,'SE','SWE',0,'Sweden')
            ,(756,'CH','CHE',0,'Switzerland')
            ,(760,'SY','SYR',0,'Syrian Arab Republic')
            ,(762,'TJ','TJK',0,'Tajikistan')
            ,(764,'TH','THA',0,'Thailand')
            ,(768,'TG','TGO',0,'Togo')
            ,(772,'TK','TKL',0,'Tokelau')
            ,(776,'TO','TON',0,'Tonga')
            ,(780,'TT','TTO',0,'Trinidad and Tobago')
            ,(784,'AE','ARE',0,'United Arab Emirates')
            ,(788,'TN','TUN',0,'Tunisia')
            ,(792,'TR','TUR',0,'Turkey')
            ,(795,'TM','TKM',0,'Turkmenistan')
            ,(796,'TC','TCA',0,'Turks and Caicos Islands')
            ,(798,'TV','TUV',0,'Tuvalu')
            ,(800,'UG','UGA',0,'Uganda')
            ,(804,'UA','UKR',0,'Ukraine')
            ,(807,'MK','MKD',0,'Macedonia (the former Yugoslav Republic of)')
            ,(818,'EG','EGY',0,'Egypt')
            ,(826,'GB','GBR',0,'United Kingdom of Great Britain and Northern Ireland')
            ,(831,'GG','GGY',0,'Guernsey')
            ,(832,'JE','JEY',0,'Jersey')
            ,(833,'IM','IMN',0,'Isle of Man')
            ,(834,'TZ','TZA',0,'Tanzania, United Republic of')
            ,(840,'US','USA',0,'United States of America')
            ,(850,'VI','VIR',0,'Virgin Islands (U.S.)')
            ,(854,'BF','BFA',0,'Burkina Faso')
            ,(858,'UY','URY',0,'Uruguay')
            ,(860,'UZ','UZB',0,'Uzbekistan')
            ,(862,'VE','VEN',0,'Venezuela (Bolivarian Republic of)')
            ,(876,'WF','WLF',0,'Wallis and Futuna')
            ,(882,'WS','WSM',0,'Samoa')
            ,(887,'YE','YEM',0,'Yemen')
            ,(894,'ZM','ZMB',0,'Zambia')
            ;
    UNLOCK TABLES;
