/*
|---------------------------------------
| Data for the `publishers` table.
|---------------------------------------
*/
    LOCK TABLES `publishers` WRITE;
    INSERT INTO `publishers`
    VALUES ( 1,'Random House')
          ,( 2,'Penguin')
          ,( 3,'Hamish Hamilton')
          ,( 4,'Allen Lane')
          ,( 5,'Michael Joseph')
          ,( 6,'Viking')
          ,( 7,'Rough Guides')
          ,( 8,'Dorling Kindersley')
          ,( 9,'Puffin')
          ,(10,'Ladybird')
          ,(11,'Warne')
          ,(12,'Century')
          ,(13,'Hutchinson')
          ,(14,'William Heinemann')
          ,(15,'Arrow')
          ,(16,'Chatto & Windus')
          ,(17,'Jonathan Cape')
          ,(18,'Harvill Secker')
          ,(19,'Vintage')
          ,(20,'Pimlico')
          ,(21,'Bodley Head')
          ,(22,'Transworld')
          ,(23,'Doubleday')
          ,(24,'Bantam Pres')
          ,(25,'Black Swan')
          ,(26,'Bantam')
          ,(27,'Corgi')
          ,(28,'Ebury Press')
          ,(29,'BBC Books')
          ,(30,'Virgin Books')
          ,(31,'Black Lace')
          ,(32,'Nexus')
          ,(33,'Cheek')
          ,(34,'Andersen Press')
          ,(35,'Hachette Livre (UK)')
          ,(36,'Headline')
          ,(37,'Hodder & Stoughton')
          ,(38,'Sceptre')
          ,(39,'Quercus')
          ,(40,'Little Brown')
          ,(41,'Abacus')
          ,(42,'Sphere')
          ,(43,'Piatkus')
          ,(44,'Orbit')
          ,(45,'Virago')
          ,(46,'Orion')
          ,(47,'Weidenfeld & Nicolson')
          ,(48,'Gollancz')
          ,(49,'Phoenix')
          ,(50,'Everyman')
          ,(51,'John Murray')
          ,(52,'Octopus')
          ,(53,'Cassell')
          ,(54,'Hamlyn')
          ,(55,'Mitchell Beazley')
          ,(56,'Philips')
          ,(57,'Orion Children\'s Books')
          ,(58,'Hodder Children’s Books')
          ,(59,'OrCHARd Books')
          ,(60,'Franklin Watts')
          ,(61,'Wayland')
          ,(62,'Hodder Education')
          ,(63,'Chambers Harrap')
          ,(64,'HarperCollins')
          ,(65,'4th Estate')
          ,(66,'Avon')
          ,(67,'Voyager')
          ,(68,'Collins')
          ,(69,'HarperPress')
          ,(70,'Blue Door')
          ,(71,'Pan Macmillan')
          ,(72,'Pan Books')
          ,(73,'Picador')
          ,(74,'Macmillan New Writing')
          ,(75,'Macmillan')
          ,(76,'Boxtree')
          ,(77,'Sidgwick and Jackson')
          ,(78,'Tor (UK)')
          ,(79,'Kingfisher')
          ,(80,'Pearson Education')
          ,(81,'Oxford University Press')
          ,(82,'Bloomsbury')
          ,(83,'A&C Black')
          ,(84,'Simon & Schuster')
          ,(85,'John Wiley & Sons (UK)')
          ,(86,'Faber Independent Allianc')
          ,(87,'Colin Smythe')
;
